### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by georgechitechi** [redbastie/larawire#1]
**Really nice Package.**
Was just wondering if in roadmap there is possibility to generate fields based on database fields.
Or define fields while creating the model and this fields are added in the migration as well as form.blade.php

Flash messages when data added or deleted world be awesome.

**Comment by maniboss** [comment]
I have a problem with **font awesome**

**Comment by redbastie** [comment]
> I have a problem with **font awesome**

If using fontawesome free, you need to npm install it and remove pro from package json, and update your app.js to point to free version.

**Comment by georgechitechi** [comment]
Also you'll need to change `far fa-` to `fa fa-` in the templates

**Comment by redbastie** [comment]
> **Really nice Package.**
> Was just wondering if in roadmap there is possibility to generate fields based on database fields.
> Or define fields while creating the model and this fields are added in the migration as well as form.blade.php
> 
> Flash messages when data added or deleted world be awesome.

I like the DB field idea, but it would only be simple generation, as in a string field would translate to a simple text input. The problem is this almost always needs customizing, so I use live templates in PHPstorm to quickly add my form stuff. I like the idea though.

As for flash messages - I find them to be anti-UX. I've spent quite a bit of time and some of my other packages has flash messages. The user already sees any errors if they occur - but I believe they should only be shown messages if there are errors. On success, it should refresh the component so they can see the updates etc.

**Comment by georgechitechi** [comment]
Alternative for now would be to have `--fields=FIELD` in the php artisan command, this to go into migrations, factories and fields, even if user have to customise field types like date, textarea, select

**Comment by redbastie** [comment]
I think it might actually be better to work like this:

You run `php artisan make:crud {model}`

Then you update your migrations in the new model.

Then you run `php artisan migrate:auto`

Then, you run something like `php artisan make:html`

The `make:html` command would then update your form fields using the columns in the database. This way you wouldnt need you create a separate config file or add a ton of arguments to the crud command.

What do you think?

**Comment by georgechitechi** [comment]
Excellent :)
